parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  browser: true
  node: true
  jquery: true
  es6: true
extends:
  - standard
  - standard-react
plugins:
  - react
  - import
globals:
  expect: false
